### ISSUE TITLE
Error on freeswitch after upgrade

### ISSUE THREAD

**Issue by davidcsi** [sipcapture/homer#243]
Hello guys,

After upgrading Homer to 5 we're seeing on freeswitch CLI:

`Error: 2017-04-24 11:50:55.458047 [ERR] switch_xml.c:1695 Error[[error near line 2174]: missing "]`

has this happened to anyone?

Our config on sofia xml is:

`<param name="capture-server" value="udp:my.capture.server:9060"/>`

This seems to only happen from fs can't send packets to homer... Is this a known error?

FS version is `FreeSWITCH (Version 1.6.18 -35-6e79667 64bit) is ready`

Thanks

**Comment by adubovikov** [comment]
Hi,

if you upgraded only homer why you see errors in the freeswitch ?

**Comment by lmangani** [comment]
Indeed seems unrelated to HOMER. If using FS 1.7+ maybe try using the full configuration format:
```
<param name="capture-server" value="udp:my.capture.server:9060;hep=3;capture_id=100"/>
```

**Comment by davidcsi** [comment]
I haven't seen this error anymore.. i hate not knowing what's going on, but... closing
